controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_hip_joint
      - right_hip_joint
      - left_foot_joint  
      - right_foot_joint 
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_foot_joint"]
    right_wheel_names: ["right_foot_joint"]
    wheel_separation: 0.05 
    wheel_radius: 0.03     
    use_stamped_vel: false