slam_toolbox:
  ros__parameters:
    # Essential Settings
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    #mode: mapping

     # LOCALIZATION
    mode: localization 
    map_file_name: /home/boris/otto_ws/src/OTTO-ROS2/otto_description/maps/serialize_map                # For the localization
    # Tell the robot roughly where it is starting (0,0 is where Gazebo spawns it)
    map_start_pose: [0.0, 0.0, 0.0]

    transform_timeout: 0.5
    # Tuning (How often it updates the map)
    map_update_interval: 1.0
    resolution: 0.05
    max_laser_range: 8.0
   

